import Link from 'next/link';

export const metadata = {
  title: 'Privacy Policy · ft_transcendence',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-neutral-950 text-neutral-200">
      <div className="mx-auto max-w-2xl px-6 py-16 sm:py-20">
        <Link
          href="/"
          className="text-sm text-neutral-500 hover:text-neutral-300 transition-colors"
        >
          ← Back
        </Link>

        <header className="mt-8 mb-12 border-b border-neutral-800 pb-8">
          <h1 className="text-3xl font-semibold tracking-tight text-white">
            Privacy Policy
          </h1>
          <p className="mt-2 text-sm text-neutral-500">Last updated [DATE]</p>
        </header>

        <article
          className="
            space-y-8
            [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-white [&_h2]:mt-10 [&_h2]:mb-3
            [&_p]:text-[15px] [&_p]:leading-7 [&_p]:text-neutral-400
            [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5 [&_ul]:text-[15px] [&_ul]:text-neutral-400
            [&_li]:leading-6
            [&_a]:text-neutral-200 [&_a]:underline [&_a]:underline-offset-2 [&_a]:decoration-neutral-700 hover:[&_a]:decoration-neutral-400
            [&_table]:w-full [&_table]:text-sm [&_table]:border-collapse
            [&_th]:text-left [&_th]:font-medium [&_th]:text-neutral-300 [&_th]:border-b [&_th]:border-neutral-800 [&_th]:pb-2
            [&_td]:py-2 [&_td]:border-b [&_td]:border-neutral-900 [&_td]:text-neutral-400 [&_td]:align-top
          "
        >
          <p>
            This Privacy Policy describes how ft_transcendence (&quot;the
            Service&quot;, &quot;we&quot;, &quot;us&quot;) collects, uses, and
            protects your personal data when you use our Pong web application.
          </p>

          <section>
            <h2>1. Who We Are</h2>
            <p>
              ft_transcendence is a student project developed as part of the 42
              School curriculum. It is not a commercial product. Contact:{' '}
              <a href="mailto:[TEAM EMAIL]">[TEAM EMAIL]</a> ·{' '}
              <a href="[GITHUB REPO LINK]">GitHub repo</a>.
            </p>
          </section>

          <section>
            <h2>2. Data We Collect</h2>
            <table>
              <thead>
                <tr>
                  <th>Data</th>
                  <th>Purpose</th>
                  <th>Source</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Username</td>
                  <td>Public identity (leaderboards, match history, friends)</td>
                  <td>You, at registration</td>
                </tr>
                <tr>
                  <td>Email address</td>
                  <td>Account login, password recovery</td>
                  <td>You, at registration</td>
                </tr>
                <tr>
                  <td>Password (hashed)</td>
                  <td>Authentication</td>
                  <td>You, at registration</td>
                </tr>
                <tr>
                  <td>Avatar image</td>
                  <td>Profile display</td>
                  <td>Uploaded by you (optional)</td>
                </tr>
                <tr>
                  <td>OAuth profile info</td>
                  <td>Login via Google</td>
                  <td>Google, if you choose OAuth login</td>
                </tr>
                <tr>
                  <td>Match history &amp; stats</td>
                  <td>Game features, leaderboards, tournaments</td>
                  <td>Generated by gameplay</td>
                </tr>
                <tr>
                  <td>IP / connection metadata</td>
                  <td>Security, abuse prevention, WebSocket sessions</td>
                  <td>Automatically, during use</td>
                </tr>
              </tbody>
            </table>
            <p>
              We do not collect payment information, and we do not sell or share
              your data with third parties for advertising.
            </p>
          </section>

          <section>
            <h2>3. How We Store Your Data</h2>
            <ul>
              <li>Passwords are hashed and never stored in plain text.</li>
              <li>Avatars are stored as encoded data in our database.</li>
              <li>
                Data is stored in a PostgreSQL database running within our
                Docker-based infrastructure.
              </li>
              <li>
                Access tokens (JWT) authenticate requests and are short-lived;
                refresh tokens are rotated on use.
              </li>
            </ul>
          </section>

          <section>
            <h2>4. Legal Basis &amp; Purpose of Processing</h2>
            <p>We process your data to:</p>
            <ul>
              <li>Provide core account and gameplay functionality (contract necessity).</li>
              <li>Secure your account (legitimate interest).</li>
              <li>Enable optional features you opt into, such as OAuth login (consent).</li>
            </ul>
          </section>

          <section>
            <h2>5. Your Rights</h2>
            <p>Under GDPR and similar frameworks, you have the right to:</p>
            <ul>
              <li>Access the personal data we hold about you.</li>
              <li>Rectify inaccurate data, e.g. via your profile settings.</li>
              <li>Erase your account and associated data (&quot;right to be forgotten&quot;).</li>
              <li>Export your data in a portable format.</li>
              <li>Object to or restrict certain processing.</li>
            </ul>
            <p>
              To exercise these rights, contact{' '}
              <a href="mailto:[TEAM EMAIL]">[TEAM EMAIL]</a> or use the in-app
              account deletion feature, if available.
            </p>
          </section>

          <section>
            <h2>6. Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active.
              If you delete your account, your personal data is removed from our
              active database within [X days], except where retention is
              required for legitimate security logging.
            </p>
          </section>

          <section>
            <h2>7. Third-Party Services</h2>
            <p>
              If you log in via Google OAuth, Google&apos;s own privacy policy
              governs the data they process on their end. We only receive the
              profile fields necessary to create or link your account: name,
              email, avatar.
            </p>
          </section>

          <section>
            <h2>8. Cookies &amp; Local Storage</h2>
            <p>
              We use tokens stored client-side solely to keep you logged in. We
              do not use tracking or advertising cookies.
            </p>
          </section>

          <section>
            <h2>9. Children&apos;s Privacy</h2>
            <p>
              This Service is not directed at children under 16. We do not
              knowingly collect data from children under this age.
            </p>
          </section>

          <section>
            <h2>10. Changes to This Policy</h2>
            <p>
              We may update this policy as the project evolves. Material changes
              will be noted with an updated &quot;Last updated&quot; date.
            </p>
          </section>

          <section>
            <h2>11. Contact</h2>
            <p>
              Questions about this policy or your data:{' '}
              <a href="mailto:[TEAM EMAIL]">[TEAM EMAIL]</a>
            </p>
          </section>
        </article>
      </div>
    </div>
  );
}